# Generated by Django 3.0.2 on 2024-06-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='book',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='publisher',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='page',
            new_name='time',
        ),
    ]
